POST http://localhost:3000/products/create 
Content-Type: application/json

{
    "name":"Nescal",
    "weight": 1,
    "imageUrl":"https://static.carrefour.com.br/medias/sys_master/images/images/hb1/h91/h00/h00/26979835445278.jpg"
}

###
PUT http://localhost:3000/products/update/5f73a19404f73a15e6fae246
Content-Type: application/json

{
    "name":"Nescal 3.0",
    "weight": 3.5,
    "imageUrl":"https://static.carrefour.com.br/medias/sys_master/images/images/hb1/h91/h00/h00/26979835445278.jpg"
}

###

GET http://localhost:3000/user/findById/5f729b55ca6d1b2ab1755b85

###

Delete http://localhost:3000/products/delete/5f739b9a27b1cc120712f99f 