@baseUrl = http://localhost:3000

# @name createProduct
POST {{baseUrl}}/products 
Content-Type: application/json

{
    "name":"Nescal",
    "weight": 1,
    "imageUrl":"https://static.carrefour.com.br/medias/sys_master/images/images/hb1/h91/h00/h00/26979835445278.jpg"
}

###

@productId = {{createProduct.response.body._id}}
PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
    "name":"Nescal 3.0",
    "weight": 3.5,
    "imageUrl":"https://static.carrefour.com.br/medias/sys_master/images/images/hb1/h91/h00/h00/26979835445278.jpg"
}

###

GET {{baseUrl}}/products/{{productId}}

###

DELETE {{baseUrl}}/products/{{productId}}
