@baseUrl = http://localhost:3000

# @name createProduct
POST {{baseUrl}}/products 
Content-Type: application/json

{
    "name":"Product",
    "weight": 1,
    "imageUrl":"https://productImage.jpg"
}

###

@productId = {{createProduct.response.body._id}}
PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
    "name":"New Product",
    "weight": 3.5,
    "imageUrl":"https://newProductImage.jpg"
}
###

GET {{baseUrl}}/products

###

GET {{baseUrl}}/products/{{productId}}

###

DELETE {{baseUrl}}/products/{{productId}}
